---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b2b-dashboard
  labels:
    app: b2b-dashboard
  namespace: pw-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: b2b-dashboard
  template:
    metadata:
      labels:
        app: b2b-dashboard
    spec:
      containers:
      - name: b2b-dashboard
        image: 593328819491.dkr.ecr.eu-west-3.amazonaws.com/b2b-dashboard:v1.0.8
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: b2b-dashboard
  namespace: pw-prod
spec:
  selector:
    app: b2b-dashboard
  ports:
  - port: 80
